esphome:
  name: poolnodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.25
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Poolnodemcu Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

switch:
  - platform: gpio
    pin: D0
    name: "thermistor_switch"
    id: "thermistor_switch"
    
  - platform: gpio
    pin: D3
    name: "Heater"
    id: "heater_d3"

  - platform: gpio
    pin: D4
    name: "Spare Relay"
    id: "spare_d4"

  - platform: gpio
    pin: D5
    name: "Step 1 - 1850 RPM"
    id: "pump_step1_d5"
    interlock: &pump_steps_interlock [pump_step1_d5, pump_step2_d6, pump_step3_d7,pump_ovrd_d8]
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D6
    name: "Step 2 - 2350 RPM"
    id: "pump_step2_d6"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D7
    name: "Step 3 - 2850 RPM"
    id: "pump_step3_d7"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D8
    name: "Override - 3450RPM"
    id: "pump_ovrd_d8"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms

i2c:
  scl: D1
  sda: D2
  scan: True
  id: bus_a

ads1115:
  - address: 0x48

sensor:
  - platform: ntc
    sensor: a0_resistance_value
    calibration:
#    https://www.thinksrs.com/downloads/programs/therm%20calc/ntccalibrator/ntccalculator.html    
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A0 Temperature

  - platform: ntc
    sensor: a1_resistance_value
    calibration:
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A1 Temperature

  - platform: ntc
    sensor: a2_resistance_value
    calibration:
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A2 Temperature

#  - platform: ntc
#    sensor: a3_resistance_value
#    calibration:
#      b_constant: 3642.74
#      reference_temperature: 20.2째C
#      reference_resistance: 12.8kOhm
#    name: A3 Temperature    

# start source data sensors
# ADS_A0 Resistance
  - platform: resistance
    id: a0_resistance_value
    sensor: a0_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A0 Resistance Sensor

# ADS_A0 Raw Value
  - platform: ads1115
    id: a0_raw_value
    multiplexer: "A0_GND"
    gain: 4.096
    name: "ADS A0-GND"
    update_interval: never

# ADS_A1 Resistance
  - platform: resistance
    id: a1_resistance_value
    sensor: a1_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A1 Resistance Sensor

# ADS_A1 Raw Value
  - platform: ads1115
    id: a1_raw_value
    multiplexer: "A1_GND"
    gain: 4.096
    name: "ADS A1-GND"
    update_interval: never
    
# ADS_A2 Resistance
  - platform: resistance
    id: a2_resistance_value
    sensor: a2_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A2 Resistance Sensor

# ADS_A2 Raw Value
  - platform: ads1115
    id: a2_raw_value
    multiplexer: "A2_GND"
    gain: 4.096
    name: "ADS A2-GND"
    update_interval: never    
    
# ADS_A3 Resistance
#  - platform: resistance
#    id: a3_resistance_value
#    sensor: a3_raw_value
#    configuration: UPSTREAM
#    resistor: 10.0kOhm
#    name: A3 Resistance Sensor

# ADS_A3 Raw Value
#  - platform: ads1115
#    id: a3_raw_value
#    multiplexer: "A3_GND"
#    gain: 4.096
#    name: "ADS A3-GND"
#    update_interval: never
# end source sensors
    
interval:
  - interval: 15s
    then:
      - switch.turn_on: thermistor_switch
      - component.update: a0_raw_value
      - component.update: a1_raw_value
      - component.update: a2_raw_value
#      - component.update: a3_raw_value
      - switch.turn_off: thermistor_switch
