esphome:
  name: poolnodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 172.27.1.80
    gateway: 172.27.1.1
    subnet: 255.255.255.0
    dns1: 172.27.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: !secret esphome_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

switch:
  - platform: gpio
    pin: D0
    name: "thermistor_switch"
    id: "thermistor_switch"
    
  - platform: gpio
    pin: D3
    name: "Heater"
    id: "heater_d3"

  - platform: gpio
    pin: D4
    name: "SWCG"
    id: "swcg_d4"

  - platform: gpio
    pin: D5
    name: "Step 1 - 1850 RPM"
    id: "pump_step1_d5"
    interlock: &pump_steps_interlock [pump_step1_d5, pump_step2_d6, pump_step3_d7,pump_ovrd_d8]
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D6
    name: "Step 2 - 2350 RPM"
    id: "pump_step2_d6"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D7
    name: "Step 3 - 2850 RPM"
    id: "pump_step3_d7"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms

  - platform: gpio
    pin: D8
    name: "Override - 3450RPM"
    id: "pump_ovrd_d8"
    interlock: *pump_steps_interlock
    interlock_wait_time: 500ms
    
## Step 1 + SWCG
  - platform: template
    name: "Step 1 with SWCG"
    lambda: |-
      if (id(pump_step1_d5).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: swcg_d4
      - switch.turn_on: pump_step1_d5
    turn_off_action:
      - switch.turn_off: swcg_d4
      - switch.turn_off: pump_step1_d5    
## Step 2 + SWCG
  - platform: template
    name: "Step 2 with SWCG"
    lambda: |-
      if (id(pump_step2_d6).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: swcg_d4
      - switch.turn_on: pump_step2_d6
    turn_off_action:
      - switch.turn_off: swcg_d4
      - switch.turn_off: pump_step2_d6
## Step 3 + SWCG
  - platform: template
    name: " Step 3 with SWCG"
    lambda: |-
      if (id(pump_step3_d7).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: swcg_d4
      - switch.turn_on: pump_step3_d7
    turn_off_action:
      - switch.turn_off: swcg_d4
      - switch.turn_off: pump_step3_d7
## Override + SWCG
  - platform: template
    name: " Step 4 OVRD with SWCG"
    lambda: |-
      if (id(pump_ovrd_d8).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: swcg_d4
      - switch.turn_on: pump_ovrd_d8
    turn_off_action:
      - switch.turn_off: swcg_d4
      - switch.turn_off: pump_ovrd_d8

i2c:
  scl: D1
  sda: D2
  scan: True
  id: bus_a

ads1115:
  - address: 0x48

sensor:
  - platform: ntc
    sensor: a0_resistance_value
    calibration:
#    https://www.thinksrs.com/downloads/programs/therm%20calc/ntccalibrator/ntccalculator.html    
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A0 Temperature

  - platform: ntc
    sensor: a1_resistance_value
    calibration:
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A1 Temperature

  - platform: ntc
    sensor: a2_resistance_value
    calibration:
      b_constant: 3642.74
      reference_temperature: 25째C
      reference_resistance: 10.0kOhm
    name: A2 Temperature

  - platform: ntc
    sensor: a3_resistance_value
    calibration:
      b_constant: 3642.74
      reference_temperature: 20.2째C
      reference_resistance: 12.8kOhm
    name: A3 Temperature    

# start source data sensors
# ADS_A0 Resistance
  - platform: resistance
    id: a0_resistance_value
    sensor: a0_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A0 Resistance Sensor

# ADS_A0 Raw Value
  - platform: ads1115
    id: a0_raw_value
    multiplexer: "A0_GND"
    gain: 4.096
    name: "ADS A0-GND"
    update_interval: never

# ADS_A1 Resistance
  - platform: resistance
    id: a1_resistance_value
    sensor: a1_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A1 Resistance Sensor

# ADS_A1 Raw Value
  - platform: ads1115
    id: a1_raw_value
    multiplexer: "A1_GND"
    gain: 4.096
    name: "ADS A1-GND"
    update_interval: never
    
# ADS_A2 Resistance
  - platform: resistance
    id: a2_resistance_value
    sensor: a2_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A2 Resistance Sensor

# ADS_A2 Raw Value
  - platform: ads1115
    id: a2_raw_value
    multiplexer: "A2_GND"
    gain: 4.096
    name: "ADS A2-GND"
    update_interval: never    
    
# ADS_A3 Resistance
  - platform: resistance
    id: a3_resistance_value
    sensor: a3_raw_value
    configuration: UPSTREAM
    resistor: 10.0kOhm
    name: A3 Resistance Sensor

# ADS_A3 Raw Value
  - platform: ads1115
    id: a3_raw_value
    multiplexer: "A3_GND"
    gain: 4.096
    name: "ADS A3-GND"
    update_interval: never
# end source sensors
    
interval:
  - interval: 30s
    then:
      - switch.turn_on: thermistor_switch
      - component.update: a0_raw_value
      - component.update: a1_raw_value
      - component.update: a2_raw_value
      - switch.turn_off: thermistor_switch
